### ISSUE TITLE
Does not compile on stable Rust 1.43.1

### ISSUE THREAD

**Issue by surban** [rexlunae/simple-endian-rs#1]
Compiling using Rust 1.43.1 gives the following error message:

```
   Compiling simple_endian v0.1.7
error[E0554]: `#![feature]` may not be used on the stable release channel
```

**Comment by halotroop2288** [comment]
This remains true to this day, with Rust Stable 1.67.1. You just can't compile this on Stable due to the nightly features.

**Comment by rexlunae** [comment]
I think this is fixed now.
